app:
  path: /
  controller: App\Controller\LoginController::index

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
pdo:
  path: /pdo
  controller: App\Controller\PDOController::index

login:
  path: /login
  controller: App\Controller\LoginController::index

accueil:
  path: /accueil
  controller: App\Controller\AccueilController::index
